#----------------------------------------------------------------------
# This file was generated by /usr/local/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

MASSIVElogoTransparent16x16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAD9GlDQ1BJQ0MgUHJvZmlsZQAA"
    "eNqNlM9vFGUYxz+7886sCTgHUwGLwYk/gJBCtmCQBkF3u8u2UMtm22LbmJjt7NvdsdPZ8Z3Z"
    "8iM9cdEbqH+Aihw8mHgywV8RLsBBAwlBQ2xITDiU+CNEEi6G1MNMdwdoxff0zPN+n+/3+zzv"
    "k4HM51Xfd9MWzHqhqpTy1vjEpJW5QZpnWEM3a6p24OfK5SGAqu+7PHLu/UwK4Nr2le//86yp"
    "ycCG1BNAsxbYs5A6Brpr+yoE4xaw52joh5B5FuhS4xOTkMkCXfUoLgBdU1E8DnSp0Uo/ZFzA"
    "tBvVGmTmgZ6pRL6eiCMPAHSVpCeVY1uVUt4qq+a048qE3cdc/88z67aW9TYBa4OZkUPAVkgd"
    "a6iBShx/YleLI8CLkLrsh/kKsBlSf7RmxnLANkg/Na0OjEX49KsnGqNvAusgXXPCwdE4f8Kb"
    "Gj4c1abPzDQPVWLMZTvonwSeh/TNhhwcivxo1GShCPSAtqnRGoj5tYPB3EhxmedEo3844tHU"
    "O9WDZaAbtPdVs3I48qydkW6pEvFrF/2wHHvQFj13eCjiFKYMiiPL+bAxOhDVit2hGo1rxeS0"
    "c2Awxs/7bnko8ibOqlZlLMZcrapiKeIRf0tvLObUN9SqhUPADtD3cyRVRdJkComNx30sKpTI"
    "Y+GjaDKNg0sJiYdE4aSeZAZnFVwZiYrjDqKOxGMRhYO9CiZSuB1jmmK9yIpdIiv2iiGxT+wR"
    "fVjiNfG62C8KIiv6xN52bTmhb1HndpvnXVpILCocIX+6u7W1o3dSve3YV07deaC6+Yhnuewn"
    "OQECZtrI7cn+L81/t6HDcV2ce+va2kvzHH7cfPVb+qJ+Xb+l39AXOgj9V31BX9BvkMPFpY5k"
    "FomDhyRIOEj2cAGXkCouv+HRTOAeUJz2Tnd3buwrp+7I94bvDXOyp5PN/pL9M3s9+2n2bPb3"
    "h6a84pS0j7SvtO+1r7VvtB+xtPPaBe0H7aL2pfZt4q1W34/225NLdCvxVpy1xDXz5kbzBbNg"
    "Pme+ZA51+Mz1Zq85YG4xC+bG9rsl9ZK9OEzgtqe6slaEG8PD4SgSRUAVF4/jD+1/XC02iV4x"
    "+NDW7hF7RdulUTQKRg7L2Gb0Gb3GQSPX8WdsMQpGn7HFKD6wdfYqHcgEKtnndqaQBMygcJhD"
    "4hIgQ3ksBOhv+seVU2+E1s5s9hUr5/uutAY9e0ePVXVdSzn1RhhYSgZSzcnaDsYnJq3oF323"
    "QgpIrbvSyYVvwL6/QLvayU224IsA1r/cyW3thqc/hnO77Zaai//5qdRPEEzv2hl9rc2DfnNp"
    "6e5myHwI9z9YWvrnzNLS/c9AW4Dz7r9ZAHF41VQqcQAAAAZiS0dEAP8A/wD/oL2nkwAAAAlw"
    "SFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGEwIuGQgsDqcAAAKySURBVDjLfZNZSNRRFMZ/"
    "/78zjuOMhUWllWhGWlAYJC22mElB2AJFb21kRETQBhXZMiBGGfXQQ0SQWSi0a0iRkbsjielM"
    "5TLNjKNm5lTujaMjztwe/m5ReV/uPeee7zsf3z0XlwMJoMtGfIedKnM9BdlVLAMo/KjcTbZU"
    "+kgEQJ2bTUIith/QqVkPVKt04IwPRyQ6GfD5EWlw/0UgG8qULsWdVJV309Q+yAetH+8Ayrsh"
    "pKSF0IseIg1uHKl6PtwKAeBE7l6FwZCv7Orz0/2O5BF18rUcMZlkMQe2NF4aiyWAtAJISRwv"
    "Gmpmxw+knbZ+jNFvJaZ2+eLkJl5oH/BkhGYUCmffLwdgcXqaBCAEOouVispmxKtPuJov0tOX"
    "jOjbhVEkoAfQRGeMe7DAGAfXf1F7OkUABF417bti2RDhcOKNakAX1I7umWOVY92M7GnT5z09"
    "CjfUns8HUCVlKgRygxvqyiQATfLjpQM29/7M58cCrPdi2sKKGdZ04jWpZ/eb+2KDuzr9D6sS"
    "tCsBhoVWBpBLVuihxgyA125rp7bIgqNFHqqb4XMV0+vzxxuztnLWzMHban72GIcDQx0A+DwC"
    "gD3VZwCIvv8SgM3hSxc93BVWYz+gEV8OMlyfg6iwIW6+0JXC5VnK9OSPe+D7GqDk7uQA8CrV"
    "bE+ytzYEmzz0TsFeFMEP6xDELO6vgHPfAYjtBaDINMKyvfT8H2/dpGFJi5ZkyzJp9Skj21Mr"
    "SM42M3NiTW71hGDjg3QA2uZC9/8GyElQRyOHrBa2pRf5awFKTBP+SuPWNWNnS4iEAFy7A0Ao"
    "XrVYSGmyIspr8T2qZifAm1pk1Shofl75GMFCpwIiaxCylCalPQQhg1aFpFejBhjwgny/8t+S"
    "L7QaALhrVGQWdpBR38e1b26OB0lSPoDLA78BJCUQI2JjrpMAAAAASUVORK5CYII=")
getMASSIVElogoTransparent16x16Data = MASSIVElogoTransparent16x16.GetData
getMASSIVElogoTransparent16x16Image = MASSIVElogoTransparent16x16.GetImage
getMASSIVElogoTransparent16x16Bitmap = MASSIVElogoTransparent16x16.GetBitmap

