#!/bin/bash

# Ubuntu 12.04 may be missing a pango modules file
# which means that the launcher won't be able to find
# any fonts (the user just sees empty rectangles instead
# of characters!).

if [ ! -f /etc/pango/pango.modules ];
then
    which pango-querymodules && mkdir -p /etc/pango
    which pango-querymodules && pango-querymodules > /etc/pango/pango.modules
fi

exit 0
